#!/bin/bash
# description: Build rootfs from repos based on environment variables
# license: MIT.

source env.al8
source docker_utils_functions
export PATH=$PATH:$PWD
# build_images "9" "0" "s390x" "micro" "srbala1"  20220527 "repos"
build_images "$al_os_version" "$al_rel_version" "$al_arch" "${1}" "$al_repo_prefix" "$al_date_suffix" "repos" "false"

echo ""
echo "Moving built images to work"
mkdir -p work
mv *.xz work