#!/bin/bash
# Author: Bala Raman <srbala@gmail.com>
#

#
# import all docker util function for build and publish
#
source docker_utils_functions

file="env.al8"
echo
echo -n "Writing ${file} ... "
print_env_header "${file}";
almaEnvBuilder  "${file}" "8" "6" "all" "all"  "devl" "today"
echo -n " done!"
echo


