#!/bin/bash
# description: Build rootfs from repos based on environment variables
# license: MIT.

source ../dock-scripts/.env_al8_build
source ../dock-scripts/image_build

# build_images "9" "0" "s390x" "micro" "srbala1"  20220527 "repos"
# build_ubi_manifest $al_os_version $al_rel_version $al_arch $al_types $al_repo_prefix $al_date_suffix "rootfs"
# build_ubi_manifest "9" "0" "micro" "quay.io/almalinuxautobot" "20220527"
build_ubi_manifest "$al_os_version" "$al_rel_version" "$al_types" "$al_repo_prefix" "$al_date_suffix"

