#!/bin/bash
# description: Build rootfs from repos based on environment variables
# license: MIT.

source env.al8
source docker_utils_functions

# build_images "9" "0" "s390x" "micro" "srbala1"  20220527 "rootfs"
build_images "$al_os_version" "$al_rel_version" "$al_arch" "$al_types" "$al_repo_prefix" "$al_date_suffix" "rootfs" "true"

echo "Build complete!"