#!/bin/bash
# Author: Bala Raman <srbala@gmail.com>
#

#
# import all docker util function for build and publish
#
source docker_utils_functions
#
getProdLibBranchPrefix "9"
# getDevlLibBranchlist "9"
