#!/bin/bash
# description: Build rootfs from repos based on environment variables
# license: MIT.

docker run --rm ${2} rpm -qa --queryformat '%{name} %{version}-%{release}\n' | grep -v pubkey | sort > rpm_al${1}_pkglist_new.log
docker run --rm ${3} rpm -qa --queryformat '%{name} %{version}-%{release}\n' | grep -v pubkey | sort > rpm_al${1}_pkglist_old.log

CMD_PYTHON=python3

if [ -x "$(command -v /usr/libexec/platform-python)" ]; then
  CMD_PYTHON=/usr/libexec/platform-python
fi
${CMD_PYTHON} gen_change_log.py rpm_al${1}_pkglist_old.log rpm_al${1}_pkglist_new.log > rpm_al${1}_change_log.log