#!/bin/bash
# Author: Bala Raman <srbala@gmail.com>
#
# Required tools: bash, git, jq
# ENV_RUNTIME environment variable for 'prod' or devl env file, which contains the branch name of rootfs files
# 
set -eu
self="$(basename "$BASH_SOURCE")"

RUN_ENV="${ENV_RUNTIME:=devl}"

# get meta data of build based on env
#curl -s -o __tmp_env -L "https://raw.githubusercontent.com/srbala/alma-docker-images/publish/library/$RUN_ENV"

#source __tmp_env
#
# import all docker util function for build and publish
#
source env.al8
source env.al9
source docker_utils_functions

# almaLibrary8Tags "al-8.6.2-20220706"
# almaLibrary9Tags "al-9.0.4-20220706"
almaLibraryHeader
almaLibrary8Tags "$al_git_publish_branch_8"
almaLibrary9Tags "$al_git_publish_branch_9"
