#!/bin/bash
# Author: Bala Raman <srbala@gmail.com>
#
# Required tools: bash, git
# 
# Takes two input dates, both EL
# 
tagdate8="$1"
tagdate9="$2"
set -eu
self="$(basename "$BASH_SOURCE")"
#
# import all docker util function for build and publish
#
source docker_utils_functions

almaLibraryHeader
almaLibrary8Tags "${tagdate8}"
almaLibrary9Tags "${tagdate9}"
